### ISSUE TITLE
Fix height of the login screen in iphone8

### ISSUE THREAD

**Issue by MamtaAditiS** [recraftrelic/recraft-react-native-shopping-app#19]
![Screenshot 2020-04-03 at 1 54 01 PM](https://user-images.githubusercontent.com/25222555/78352686-62377f00-75c6-11ea-8595-6abdfa93b20a.png)

**Comment by MamtaAditiS** [comment]
![Screenshot 2020-04-03 at 1 54 01 PM](https://user-images.githubusercontent.com/25222555/78352518-12f14e80-75c6-11ea-8cbc-45bc2bb98c92.png)

**Comment by MamtaAditiS** [comment]
![Screenshot 2020-04-03 at 1 54 01 PM](https://user-images.githubusercontent.com/25222555/78352574-2e5c5980-75c6-11ea-8f58-81a2b97aea27.png)

**Comment by yashkapoor8710** [comment]
I have fixed the issue in iphone 8
https://github.com/recraftrelic/recraft-react-native-shopping-app/pull/21

**Comment by yashkapoor8710** [comment]
![Screenshot 2020-04-03 at 6 00 32 PM](https://user-images.githubusercontent.com/59904360/78360837-04f6fa00-75d5-11ea-97a5-91e2e8546083.png)

![Screenshot 2020-04-03 at 6 01 16 PM](https://user-images.githubusercontent.com/59904360/78360903-1f30d800-75d5-11ea-81f8-3ae429bb1839.png)
