### ISSUE TITLE
Text issues in product screens iphone 8

### ISSUE THREAD

**Issue by MamtaAditiS** [recraftrelic/recraft-react-native-shopping-app#20]
![Screenshot 2020-04-03 at 1 54 30 PM](https://user-images.githubusercontent.com/25222555/78352764-898e4c00-75c6-11ea-9ae2-ccf78b9ca444.png)
![Screenshot 2020-04-03 at 1 54 49 PM](https://user-images.githubusercontent.com/25222555/78352775-8f842d00-75c6-11ea-8b5e-7021dd11f280.png)

**Comment by yashkapoor8710** [comment]
![Screenshot 2020-04-03 at 5 34 07 PM](https://user-images.githubusercontent.com/59904360/78358749-54d3c200-75d1-11ea-8eba-6b988973b72c.png)


![Screenshot 2020-04-03 at 5 32 59 PM](https://user-images.githubusercontent.com/59904360/78358650-2e158b80-75d1-11ea-9fd4-c11d32954a17.png)

**Comment by yashkapoor8710** [comment]
I have fixed this issue in Iphone 8
https://github.com/recraftrelic/recraft-react-native-shopping-app/pull/21
